project_id  = "terraform-vm-project-477405"
region      = "us-central1"
zone        = "us-central1-a"
vm_name     = "jenkins-vm"
ssh_user    = "sweth"
ssh_public_key_path = "keys/id_ed25519.pub"
gcp_credentials_file = "gcp-sa.json"
