project_id  = "terraform-vm-project-477405"
region      = "us-central1"
zone        = "us-central1-a"
vm_name     = "jenkins-vm"
ssh_user    = "swathi"
ssh_public_key_path = "C:/Users/sweth/.ssh/id_rsa.pub"
